name: Main
version: '${project.version}'
main: mainpackage.main.Main
api-version: 1.19
commands:
  hub1:
    description: oyuncuyu hub 1 e ışınlar.
  hub2:
    description: oyuncuyu hub 2 ye ışınlar.
  hub3:
    description: oyuncuyu hub 3 e ışınlar.
  hub:
    description: oyuncuyu hub a ışınlar.
